[[main]]
    # Top-level menu entry
    identifier = "sauce"
    name = "sauce"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    parent = "sauce"
    weight = 1

[[main]]
    identifier = "about"
    name = "about me"
    url = "/about/"
    parent = "sauce"
    weight = 2

#[[main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    parent = "sauce"
#    weight = 3

#[[main]]
    # Top-level menu entry
    #identifier = "writing"
    #name = "Writing"
    #url = "/posts/"
    #weight = 4

[[main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    parent = "sauce"
    weight = 4

#[[main]]
#    identifier = "subsection"
#    name = "Subsection"
#    url = "/subsection/"
#    # url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
#    parent = "writing"
#    weight = 5

[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "search"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "series"
    url = "/series/"
    parent = "explore"
    weight = 8

[[main]]
    identifier = "project-type"
    name = "project types"
    url = "/project-types/"
    parent = "explore"
    weight = 9